services:
  - type: web
    name: achx-automation-chatbot-api
    env: python
    buildCommand: pip install -r requirements.txt
    # FINAL FIX: Changed startCommand to point to src.app:app
    startCommand: gunicorn --bind 0.0.0.0:$PORT src.app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0


